--[[
	Rojo: src/datatable/CostumeData.luau → ServerStorage.DataTable.CostumeData
]]

return {
	costumes = {
		["Costume_01"] = { id = "Costume_01", modelName = "hakuflower", iconAssetId = "rbxassetid://83742640505148", costType = "Gem", costAmount = 300 },
		["Costume_02"] = { id = "Costume_02", modelName = "lspeeddasher", iconAssetId = "rbxassetid://116217015819016", costType = "Gem", costAmount = 300 },
		["Costume_03"] = { id = "Costume_03", modelName = "wexiilexi- Yay!!", iconAssetId = "rbxassetid://135501883903038", costType = "Gem", costAmount = 300 },
		["Costume_04"] = { id = "Costume_04", modelName = "Deexducks", iconAssetId = "rbxassetid://88880225539306", costType = "Gem", costAmount = 300 },
		["Costume_05"] = { id = "Costume_05", modelName = "ice", iconAssetId = "rbxassetid://125031993693710", costType = "Gem", costAmount = 300 },
		["Costume_06"] = { id = "Costume_06", modelName = "Bloxikin", iconAssetId = "rbxassetid://131037298620514", costType = "Gem", costAmount = 300 },
		["Costume_07"] = { id = "Costume_07", modelName = "DarthNick_plays", iconAssetId = "rbxassetid://129795102299395", costType = "Gem", costAmount = 300 },
		["Costume_08"] = { id = "Costume_08", modelName = "Dummy", iconAssetId = "rbxassetid://72032783577556", costType = "Gem", costAmount = 300 },
		["Costume_09"] = { id = "Costume_09", modelName = "umaloka8", iconAssetId = "rbxassetid://114296791456429", costType = "Gem", costAmount = 300 },
		["Costume_10"] = { id = "Costume_10", modelName = "EnjoiUrLunch", iconAssetId = "rbxassetid://120121181830819", costType = "Gem", costAmount = 300 },
	},
}
